### ES6 高阶 一 

让正方形移动，思路

```
写一个动画效果，先向右，然后向下，然后向左，最后向上，怎么做
getComputedStyle 可以获得 left、top, 指定值，可以让往右，往下，等移动

通过 ele.style 修改位置

如果不写回调怎么办
如果不是写在回调中的运动，是如何进行的？
```

#### 自己写，问题在哪

fn  和 window.requestAnimationFrame 顺序反了

如果不在回调中写，

​	会直接跑到，最后的位置

Q:看第二遍思考，所以使用requestAnimationFrame 到底是不是循环调用？
是相当于 setInterval(,16) 么？
为什么可以一直执行？

我的理解是相当于 setTimeout(fn, 16.7) 之所以一直执行，是代码里重复调用了自身的原因

​		
**requestAnimationFrame**

60帧/秒， 16ms 执行一次

如何控制它的速度，可以用取余的方式， num%10 == 1, 调用

底层调用GPU，性能更高


**专门做动画的，为什么做动画比 setTimeout 和 setInterval 好？**

requestAnimationFrame是浏览器用于定时循环操作的一个接口，类似于setTimeout，主要用途是按帧对网页进行重绘。

在 requestAnimationFrame 之前，主要借助 setTimeout/ setInterval 来编写 JS 动画，而动画的关键在于动画帧之间的时间间隔设置，这个时间间隔的设置有讲究，一方面要足够小，这样动画帧之间才有连贯性，动画效果才显得平滑流畅；另一方面要足够大，确保浏览器有足够的时间及时完成渲染。

显示器有固定的刷新频率（60Hz或75Hz），也就是说，每秒最多只能重绘60次或75次，requestAnimationFrame的基本思想就是与这个刷新频率保持同步，利用这个刷新频率进行页面重绘。此外，使用这个API，一旦页面不处于浏览器的当前标签，就会自动停止刷新。这就节省了CPU、GPU和电力。

requestAnimationFrame是在主线程上完成。这意味着，如果主线程非常繁忙，requestAnimationFrame的动画效果会大打折扣。

requestAnimationFrame使用一个回调函数作为参数。这个回调函数会在浏览器重绘之前调用。
​
​
与setTimeout和setInterval不同，requestAnimationFrame不需要设置时间间隔

requestAnimationFrame采用系统时间间隔，保持最佳绘制效率。

不会因为间隔时间过短，造成过度绘制，增加开销；

也不会因为间隔时间太长，使用动画卡顿不流畅，有一个统一的刷新机制，从而节省系统资源，提高系统性能，改善视觉效果

requestAnimationFrame的用法与settimeout很相似，只是不需要设置时间间隔而已。	
​	
**​自己的总结：**

​	开始是使用setTimeout 和 setInterval 绘制动画，但是都有不足，setInterval并不能保证两个函数执行时间相差 timer，如果fn执行时间过长，可能会导致第一个的fn没执行完，执行栈中也有最新push的fn，那么中间会存在某些没有push进执行栈的fn

如果想要保证动画的流畅性，timer不能过大，但是也不能过小，如果小于100/60 = 16，可能会导致掉帧的现象

16，16，16，16

10，10，10

所以使用requestAnimationFrame 来绘制动画，频率和显示器频率一致

此外，使用这个API，一旦页面不处于浏览器的当前标签，就会自动停止刷新。这就节省了CPU、GPU和电力。

在主线程上完成，而不是去执行栈。






https://zhuanlan.zhihu.com/p/110772341

**setTimeout 是 在 timer 后一定执行么？**

不一定

```
btn.onclick = function(){
    setTimeout(function(){
        console.log(1);
    },250);
}
```
点击该按钮后，首先将onclick事件处理程序加入队列。该程序执行后才设置定时器，再有250ms后，指定的代码才被添加到队列中等待执行。 如果上面代码中的onclick事件处理程序执行了300ms，那么定时器的代码至少要在定时器设置之后的300ms后才会被执行。队列中所有的代码都要等到javascript进程空闲之后才能执行，而不管它们是如何添加到队列中的。



**为什么setTimeout 不能设置 16.7 ms 以下？**

https://zhuanlan.zhihu.com/p/45201506


可以看到，屏幕并没有展示left=2px的那一帧画面，图像直接从1px的位置跳到了3px的位置，这就是丢帧的现象，这种现象就会引起动画卡顿。

同样的，显示器16.7刷新间隔之前发生了其他绘制请求(setTimeout)，导致所有第三帧丢失，继而导致动画断续显示（堵车的感觉），这就是过度绘制带来的问题。不仅如此，这种计时器频率的降低也会对电池使用寿命造成负面影响，并会降低其他应用的性能。

这也是为何setTimeout的定时器推荐最小使用16.7ms的原因（16.7 = 1000/60，每秒60帧）。






#### promise

一般写promise中，会做一些异步操作，不是异步的，写会没有意义

```
let p = new Promise(()=>{
	setTimeout(fn(){
		resolve()
	}, 1000)
})
```


**then 的返回3种情况**

 - then的返回值，会返回一个新的 Promise 对象, 但是状态会有几种情况:
    - then 的回调函数中没有返回值，then就会返回一个状态为: resolved 的 promise 对象
    - then 的回调函数返回值是 非 promise 的值, then就会返回一个状态为: resolved 的 promise 对象，另外会把返回值，传递给 下一个 then
    - then 的回调函数返回值是 promise 对象，then 就直接返回这个  promise 对象，具体的状态可以由我们自己定义,具体传递的值，也由我们自己定义

```
Promise.resolve('hello');
// 相当于
const promise = new Promise(resolve => {
   resolve('hello');
});
```



**使用promise 去写， loadImage 方法**	
这是个异步过程		
之前是怎么做的，成功之后的回调，失败之后的回调	
	

	注意点：
	一定是返回一个promise，然后可以链式调用


使用 promise 去改造运动 状态。
​	

​	每次一定是返回一个 新的的 promise， move 运动

自己写错了！

	每次一定是返回一个 新的的 promise， move 运动
	自己写错了！
	这样才能链式调用

​	
async await 是异步函数，同步写法

1. 奇怪，如果第一个 await 报错，后面都不执行了吗？
	
		！！！任何一个await语句后面的 Promise 对象变为reject状态，那么整个async函数都会中断执行。

		有时，我们希望即使前一个异步操作失败，也不要中断后面的异步操作。
		
		这时可以将第一个await放在try...catch结构里面，这样不管这个异步操作是否成功，第二个await都会执行。

	那是不是每个 awiat 都要加上，try...catch ?

	```
function mypromise(type) {
	    return new Promise((resolve, reject)=>{
	        if(type == 1) {
	            resolve()
	            console.log('正确',type)
	        }
	        else {
	            reject()
	            console.log('错误',type)
	        }
	    })
	}
	
	async function myasync2() {
	    try{
	        await mypromise(2);
	    } catch(e) {
	        console.log('catch', e)
	    } 
	    await mypromise(2);  //这里依然会报错
	    await mypromise(1);  // 这里不会执行
	}
	
	myasync2();
	```
	
	[如何如何优雅地处理Async/Await的异常](https://zhuanlan.zhihu.com/p/79118227)
	
	结论：抽出来两个方法，一个用来返回promise 对象，一个用来 then 捕获 data, catch 捕获错误，通过赋值解构拿到，第二个封装方法的返回值
	
	```
	(async () => {
	    const fetchData = () => {
	        return new Promise((resolve, reject) => {
	            setTimeout(() => {
	                resolve('fetch data is me')
	            }, 1000)
	        })
	    }
	
	    // 抽离成公共方法
	    const awaitWrap = (promise) => {
	        return promise
	            .then(data => [null, data])
	            .catch(err => [err, null])
	    }
	
	    const [err, data] = await awaitWrap(fetchData())
	    console.log('err', err)
	    console.log('data', data)
	    // err null
	    // data fetch data is me
	})()
	
	注意，不能是返回 new promise().then().catch()  返回的是一个promise 对象，而不是值
	```
	
2. 回顾下，promise catch

    ```
    // 写法一
    const promise = new Promise(function(resolve, reject) {
      try {
        throw new Error('test');
      } catch(e) {
        reject(e);
      }
    });
    
    等价于：可以发现reject()方法的作用，等同于抛出错误
    
    // 写法二
    const promise = new Promise(function(resolve, reject) {
      reject(new Error('test'));
    });
    

    //注意这种情况，不行因为返回任意一个非 promise 的值都会被包裹成 promise 对象，即 return new Error('error!!!') 等价于 return Promise.resolve(new Error('error!!!'))。

    Promise.resolve()
	  .then(() => {
    	    return new Error('error!!!')
	  })
    	  .catch((err) => {
    	    console.log('catch: ', err)
    	  })
    
    ```
    
    Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个`catch`语句捕获。
    

一般来说，不要在`then()`方法里面定义 Reject 状态的回调函数（即`then`的第二个参数），总是使用`catch`方法。
    
跟传统的`try/catch`代码块不同的是，如果没有使用`catch()`方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。
    
    ```
    const someAsyncThing = function() {
      return new Promise(function(resolve, reject) {
        // 下面一行会报错，因为x没有声明
        resolve(x + 2);
      });
    };
    ```
    
    这就是说，Promise 内部的错误不会影响到 Promise 外部的代码，通俗的说法就是“Promise 会吃掉错误”。
    
    一般总是建议，Promise 对象后面要跟`catch()`方法，这样可以处理 Promise 内部发生的错误。`catch()`方法返回的还是一个 Promise 对象，因此后面还可以接着调用`then()`方法。





**promise 的静态方法**

	resolove()、reject()
	
	Promise.all([p1, p2, p3]);
	
	all 和 race 返回的 参数是什么


​	

all 是 返回的数组

	（1）只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。
	
	（2）只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。
	所以要捕获这个错误，需要在后面加上 catch

我们可以根据race这个属性做超时的操作：

第二个是参数是，timer 后，变成 reject的promise

```
//请求某个图片资源
let requestImg = new Promise(function(resolve, reject){
        var img = new Image();
        img.onload = function(){
            resolve(img);
        }
    });
//延时函数，用于给请求计时
let timeOut = new Promise(function(resolve, reject){
        setTimeout(function(){
            reject('图片请求超时');
        }, 5000);
    });

Promise.race([requestImg, timeout]).then((res)=>{
    console.log(res);
}).catch((err)=>{
    console.log(err);
});
```

promise 值穿透

then 方法接受的参数是函数，而如果传递的并非是一个函数，它实际上会将其解释为 then(null)，这就会导致前一个 Promise 的结果会穿透下面。 

```
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .then(console.log)  //1
```

promise.finally

不管promise最后的状态，在执行完then或catch指定的回调函数以后，都会执行finally方法指定的回调函数。



then 或者 catch 不能返回自身，否则会造成死循环

```
const promise = Promise.resolve()
  .then(() => {
    return promise
  })
promise.catch(console.error)
```



参考文章：

https://www.cnblogs.com/fengxiongZz/p/8191503.html
